language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn build
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN -e REACT_APP_KEY=$API_TOKEN
    skip_cleanup: true
    on:
      all_branches: true